type EventHandlerFunction<E extends Event> = (event: E) => void;

export type { EventHandlerFunction };
export interface EventHandlerAttributes {
  // onabort?: EventHandlerFunction<Event>;
  // onautocomplete?: EventHandlerFunction<Event>;
  // onautocompleteerror?: EventHandlerFunction<Event>;
  // onblur?: EventHandlerFunction<Event>;
  // oncancel?: EventHandlerFunction<Event>;
  // oncanplay?: EventHandlerFunction<Event>;
  // oncanplaythrough?: EventHandlerFunction<Event>;
  onchange?: EventHandlerFunction<Event>;
  onclick?: EventHandlerFunction<MouseEvent>;
  // onclose?: EventHandlerFunction<Event>;
  // oncontextmenu?: EventHandlerFunction<Event>;
  // oncuechange?: EventHandlerFunction<Event>;
  // ondblclick?: EventHandlerFunction<Event>;
  // ondrag?: EventHandlerFunction<Event>;
  // ondragend?: EventHandlerFunction<Event>;
  // ondragenter?: EventHandlerFunction<Event>;
  // ondragexit?: EventHandlerFunction<Event>;
  // ondragleave?: EventHandlerFunction<Event>;
  // ondragover?: EventHandlerFunction<Event>;
  // ondragstart?: EventHandlerFunction<Event>;
  // ondrop?: EventHandlerFunction<Event>;
  // ondurationchange?: EventHandlerFunction<Event>;
  // onemptied?: EventHandlerFunction<Event>;
  // onended?: EventHandlerFunction<Event>;
  // onerror?: EventHandlerFunction<Event>;
  // onfocus?: EventHandlerFunction<Event>;
  // oninput?: EventHandlerFunction<Event>;
  // oninvalid?: EventHandlerFunction<Event>;
  onkeydown?: EventHandlerFunction<KeyboardEvent>;
  // onkeypress?: EventHandlerFunction<Event>;
  // onkeyup?: EventHandlerFunction<Event>;
  // onload?: EventHandlerFunction<Event>;
  // onloadeddata?: EventHandlerFunction<Event>;
  // onloadedmetadata?: EventHandlerFunction<Event>;
  // onloadstart?: EventHandlerFunction<Event>;
  // onmousedown?: EventHandlerFunction<Event>;
  // onmouseenter?: EventHandlerFunction<Event>;
  // onmouseleave?: EventHandlerFunction<Event>;
  // onmousemove?: EventHandlerFunction<Event>;
  // onmouseout?: EventHandlerFunction<Event>;
  // onmouseover?: EventHandlerFunction<Event>;
  // onmouseup?: EventHandlerFunction<Event>;
  // onmousewheel?: EventHandlerFunction<Event>;
  // onpause?: EventHandlerFunction<Event>;
  // onplay?: EventHandlerFunction<Event>;
  // onplaying?: EventHandlerFunction<Event>;
  // onprogress?: EventHandlerFunction<Event>;
  // onratechange?: EventHandlerFunction<Event>;
  // onreset?: EventHandlerFunction<Event>;
  // onresize?: EventHandlerFunction<Event>;
  // onscroll?: EventHandlerFunction<Event>;
  // onseeked?: EventHandlerFunction<Event>;
  // onseeking?: EventHandlerFunction<Event>;
  // onselect?: EventHandlerFunction<Event>;
  // onshow?: EventHandlerFunction<Event>;
  // onsort?: EventHandlerFunction<Event>;
  // onstalled?: EventHandlerFunction<Event>;
  // onsubmit?: EventHandlerFunction<Event>;
  // onsuspend?: EventHandlerFunction<Event>;
  // ontimeupdate?: EventHandlerFunction<Event>;
  // ontoggle?: EventHandlerFunction<Event>;
  // onvolumechange?: EventHandlerFunction<Event>;
  // onwaiting?: EventHandlerFunction<Event>;
}
